java -jar ../saxon9.jar -versionmsg:off -s:examples/ex01.xml -o:output/result_ex01.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex02.xml -o:output/result_ex02.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex03.xml -o:output/result_ex03.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex04.xml -o:output/result_ex04.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex05.xml -o:output/result_ex05.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex06.xml -o:output/result_ex06.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex07.xml -o:output/result_ex07.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex08.xml -o:output/result_ex08.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex09.xml -o:output/result_ex09.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex10.xml -o:output/result_ex10.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex11.xml -o:output/result_ex11.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex12.xml -o:output/result_ex12.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex13.xml -o:output/result_ex13.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex14.xml -o:output/result_ex14.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex15.xml -o:output/result_ex15.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex16.xml -o:output/result_ex16.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex17.xml -o:output/result_ex17.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex18.xml -o:output/result_ex18.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex19.xml -o:output/result_ex19.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex20.xml -o:output/result_ex20.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex21.xml -o:output/result_ex21.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex22.xml -o:output/result_ex22.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex23.xml -o:output/result_ex23.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex24.xml -o:output/result_ex24.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex25.xml -o:output/result_ex25.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex26.xml -o:output/result_ex26.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex27.xml -o:output/result_ex27.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex28.xml -o:output/result_ex28.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex29.xml -o:output/result_ex29.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex30.xml -o:output/result_ex30.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex31.xml -o:output/result_ex31.xml -xsl:output/val_schema.xsl
java -jar ../saxon9.jar -versionmsg:off -s:examples/ex32.xml -o:output/result_ex32.xml -xsl:output/val_schema.xsl
