//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.30 at 09:10:51 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:mpeg:dash:schema:mpd:2011", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.iso.mpeg.dash;
